# -*- coding: utf-8 -*-
# Generated by Django 1.11.3 on 2017-09-13 07:32
from __future__ import unicode_literals

import datetime
from django.db import migrations, models
from django.utils.timezone import utc


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0007_auto_20170913_0219'),
    ]

    operations = [
        migrations.AlterField(
            model_name='comment',
            name='created_date',
            field=models.DateTimeField(default=datetime.datetime(2017, 9, 13, 7, 32, 27, 750364, tzinfo=utc)),
        ),
    ]
