# -*- coding: utf-8 -*-
# Generated by Django 1.11.3 on 2017-09-15 02:18
from __future__ import unicode_literals

import datetime
from django.db import migrations, models
from django.utils.timezone import utc


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0009_auto_20170913_0234'),
    ]

    operations = [
        migrations.AlterField(
            model_name='comment',
            name='created_date',
            field=models.DateTimeField(default=datetime.datetime(2017, 9, 15, 2, 18, 48, 179069, tzinfo=utc)),
        ),
    ]
